### PR TITLE
Updated User Namespace to match the new Laravel 8 update

### PR DESCRIPTION
**Pull request by assellalou**
Hello, 
I made thi change to make the registration stub match the new Laravel changes that has been made on the Models location 
from \App\User into \App\Models\User

### CODE REVIEW

**Comment by driesvints** [comment]
This was already attempted and reverted. We're working on fixing this.

**Comment by assellalou** [comment]
I just don't get it,  just did the same thing I tried to do lol, why is that ?

**Comment by driesvints** [comment]
@assellalou please use laravel/ui:^3.0 which was just released and fixes this.

**Comment by assellalou** [comment]
Agh I waj just trying to contribute man, I wished it would get merged and u just closed it and did the same thing I did lol. not fair 😭😭

**Pull request closed without merging**
